#!/usr/bin/env python3

# Copyright © 2022 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

import argparse
import contextlib
import sys

import lxml.html

if sys.version_info < (3, 4):
    raise RuntimeError('Python >= 3.4 is required')

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('attrs', metavar='ATTR', nargs='+')
    options = ap.parse_args()
    doc = lxml.html.parse(sys.stdin.buffer)
    for elt in doc.iter():
        for attr in options.attrs:
            with contextlib.suppress(KeyError):
                del elt.attrib[attr]
    html = lxml.html.tostring(doc, encoding='UTF-8')
    sys.stdout.buffer.write(html)
    if html[-1] != '\n':
        sys.stdout.buffer.write(b'\n')

if __name__ == '__main__':
    main()

# vim:ts=4 sts=4 sw=4 et
