#!/usr/bin/env python3

# Copyright © 2022 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

import argparse
import sys

import lxml.html.builder

0_0  # Python >= 3.6 is required

h_head = '''
<html>
<head>
<title></title>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
</head>
<body>
'''.strip()

h_tail = '''
</body>
</html>
'''.strip()

def hprint(elt):
    s = lxml.html.tostring(elt, encoding='UTF-8')
    sys.stdout.buffer.write(s)
    sys.stdout.buffer.write(b'\n')

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('paths', metavar='FILE', nargs='+')
    opts = ap.parse_args()
    print(h_head, flush=True)
    for path in opts.paths:
        with open(path, 'rb') as fp:
            doc = lxml.html.parse(fp)
        title_elt = doc.find('//head/title')
        if title_elt is None:
            print(f'{path}: <title> element not found', file=sys.stderr)
            title = ''
        else:
            title = title_elt.text
        h1 = lxml.html.builder.H1(title)
        h1.attrib['data-origin'] = path
        hprint(h1)
        body = doc.find('body')
        body.tag = 'div'
        body.attrib['data-tag'] = 'body'
        hprint(body)
    print(h_tail)

if __name__ == '__main__':
    main()

# vim:ts=4 sts=4 sw=4 et
