#!/usr/bin/env python3
# encoding=UTF-8

# Copyright © 2020 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

import argparse

import lxml.html

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('-b', '--base-url', metavar='URL')
    ap.add_argument('path', metavar='FILE')
    options = ap.parse_args()
    with open(options.path, 'rb') as fp:
        doc = lxml.html.parse(fp)
        doc_root = doc.getroot()
        doc_root.make_links_absolute(options.base_url)
        for _, _, url, _ in doc_root.iterlinks():
            print(url)

if __name__ == '__main__':
    main()

# vim:ts=4 sts=4 sw=4 et
